[package]
name = "cargo-patch-test-other-dependency"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]

[dependencies]
cargo-patch-test-dependency = { git = "https://github.com/hannobraun/cargo-patch-test-original-dependency" }

